version: 2

workflows:
  version: 2
  build-master:
    jobs:
      - test:
          filters:
            branches:
              only: master
      - build-and-deploy:
          requires:
            - test
  build-fork:
    jobs:
      - test:
      - test:
          type: approval
          filters:
            branches:
              only: /pull\/[0-9]+/
  build-other-branches:
    jobs:
      - test:
          filters:
            branches:
              ignore: 
                - master
                - /pull\/[0-9]+/

jobs:
  test:
    docker:
      - image: node:10-alpine
    steps:
      - checkout    
  build-and-deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      
