# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2

workflows:
  version: 2
  build-master:
    jobs:
      - test:
          filters:
            branches:
              only: master
      - build-and-deploy:
          requires:
            - test
  welcome:
    jobs:
      - test:
          type: approval
          filters:
            branches:
              only: /pull\/[0-9]+/
  build-other-branches:
    jobs:
      - test:
          filters:
            branches:
              ignore: master 

jobs:
  test:
    echo "Hello test"

  build-and-deploy:
    echo "Hello build-and-deploy"
      